name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "hello there"
      - name: Second step
        run: echo "second step"