name: Output information
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main # main
      - 'dev-*' # dev-new dev-this-new
      - 'feat-**' # feat-new/ feat/new/button
    paths:
      - ".github/workflows/*"
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "${{ toJSON(github) }}"