name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "something"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo another
        run: echo "another"