name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
      - name: Maven version
        run: mvn -v
      - name: Run the tests
        run: mvn clean package