name: Test
on: push
# a simple comment
# another comment
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "something"
  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Echo another
        run: echo "another"